version: "3.10"
services:
  tweeter:
    build: .
    environment:
      NODE_ENV: "production"
      TWITTER_ENABLED: "false"
      PROMETHEUS_URL: "https://falkenstein.alexswilliams.co.uk/prometheus"
      BASIC_AUTH: "<redacted>"
    ports:
      - "8080:8080"
